### ISSUE TITLE
Please upgrade to the version of Autofac.Extras.CommonServiceLocator.

### ISSUE THREAD

**Issue by popsams** [autofac/Autofac.Extras.CommonServiceLocator#12]
Please upgrade to the version of Autofac.Extras.CommonServiceLocator.

The detected package version is outside the dependency constraint: Autofac. Extras. CommonServiceLocator 6.0.1 requires Autofac (>=5.0.0&&<7.0.0), but version Autofac 7.0.0 has been resolved

**Comment by tillig** [comment]
Wrong repo. This is for core Autofac only.

**Comment by tillig** [comment]
PR #11 should address this.

**Comment by tillig** [comment]
Resolved by #11 and #13. Will release shortly.
