### ISSUE TITLE
.NET Standard Support

### ISSUE THREAD

**Issue by justinyoo** [autofac/Autofac.Extras.CommonServiceLocator#3]
Hi, Team.

I know this is a known issue that this library can't support .NET Standard because [CommonServiceLocator](https://www.nuget.org/packages/CommonServiceLocator/) doesn't support it. The related issue was mentioned at https://github.com/autofac/Autofac/issues/859.

Therefore, just in case anyone wants to find out a solution, I forked this repo and made some changes support .NET Standard. Here are the NuGet packages:

* https://www.nuget.org/packages/Aliencube.Autofac.Extras.CommonServiceLocator/
* https://www.nuget.org/packages/Aliencube.CommonServiceLocator/

HTH

**Comment by tillig** [comment]
Sounds good!

**Comment by tillig** [comment]
CommonServiceLocator 1.4 was released with `netstandard2.0` support. Updated and [released Autofac.Extras.CommonServiceLocator 4.1.0.](https://www.nuget.org/packages/Autofac.Extras.CommonServiceLocator/4.1.0)
