### ISSUE TITLE
Port to Netstandard2.0?

### ISSUE THREAD

**Issue by solvingj** [autofac/Autofac.Extras.CommonServiceLocator#4]
Any chance this library will be ported to Netstandard2.0 since it's out now?

**Comment by tillig** [comment]
Duplicate of #3

We can't support anything that CommonServiceLocator itself doesn't support.

**Comment by tillig** [comment]
CommonServiceLocator 1.4 was released with `netstandard2.0` compatibility. [Released compatible Autofac.Extras.CommonServiceLocator 4.1.0.](https://www.nuget.org/packages/Autofac.Extras.CommonServiceLocator/4.1.0)

**Comment by solvingj** [comment]
I really appreciate you posting this here for posterity!
