### ISSUE TITLE
Autofac.Extras.CommonServiceLocator not compatible with CommonServiceLocator 1.4

### ISSUE THREAD

**Issue by eman1986** [autofac/Autofac.Extras.CommonServiceLocator#5]
CommonServiceLocator recently updated to version 1.4 and now Autofac is not working

> [CS0266] Cannot implicitly convert type 'Autofac.Extras.CommonServiceLocator.AutofacServiceLocator' to 'Microsoft.Practices.ServiceLocation.IServiceLocator'. An explicit conversion exists (are you missing a cast?)

**Comment by tillig** [comment]
Do you have some additional info? Repro? Unit test? Is the error happening in your project or when you try to build this project from source? If it's in your project, do you have the appropriate assembly binding redirects if needed?

**Comment by h82258652** [comment]
I get the same error after I update CommonServiceLocator package to 1.4.
```C#
var autofacServiceLocator = new AutofacServiceLocator(new ContainerBuilder().Build());
ServiceLocator.SetLocatorProvider(() => autofacServiceLocator); // the compiler display ()=> autofacServiceLocator has error
```

**Comment by tillig** [comment]
It seems the only change was to add more targeting for frameworks. VS is notorious for caching things, as I've seen in other projects where folks upgraded from ASP.NET Core 1.x to ASP.NET Core 2.x.

Did you try fully cleaning (including `.vs` folder, `.csproj.user` files, `.suo` files, NuGet cache, etc.) and rebuilding?

That said, there have been requests in the recent past to allow this library to support .NET standard and the thing standing in our way was that CommonServiceLocator didn't support .NET standard. Now that it does, it seems like a good opportunity to upgrade and enable that support.

**Comment by tillig** [comment]
Code committed to `develop` for the update but there seems to be some AppVeyor problem connecting to GitHub. All auth operations are timing out so it can't read the source repo and I can't log in with my GitHub account to see what's up. I'll have to wait until that's resolved before I can do more.

**Comment by eman1986** [comment]
I have done that and still I get that message, I've gone back to 1.3 until this is resolved

**Comment by tillig** [comment]
[Released as Autofac.Extras.CommonServiceLocator 4.1.0.](https://www.nuget.org/packages/Autofac.Extras.CommonServiceLocator/4.1.0)

**Comment by eman1986** [comment]
That solved it for me, thanks for the quick turnaround
