### ISSUE TITLE
Using the latest version 4.1.0, but raised the CommonServiceLocator 1.4 cannot be resolved

### ISSUE THREAD

**Issue by dflyingliu** [autofac/Autofac.Extras.CommonServiceLocator#6]
by using the latest version(4.1.0) and the CommonServiceLocator 2.0.1, which raising the expected Microsoft.Practices.ServiceLocation 1.4 cannot be founded.
then I try to get CommonServiceLocator v1.4, but there is no version 1.4. can please build the version with CommonServiceLocator 2.0.1 for .net framework 4.5?

**Comment by tillig** [comment]
[It appears they published that version and delisted it later.](https://github.com/unitycontainer/commonservicelocator/issues/14) Let me see what I can do.

**Comment by tillig** [comment]
@dflyingliu They restored the NuGet listing. Try it now.

**Comment by v-kabanov** [comment]
It now does not build with
> Reference to type 'ServiceLocatorImplBase' claims it is defined in 'CommonServiceLocator', but it could not be found

Need to change using directive for v.2.0.1 in AutofacServiceLocator.cs, line 5, should be
using CommonServiceLocator;

**Comment by tillig** [comment]
Which package versions are you using?

**Comment by v-kabanov** [comment]
Latest available at the time - 4.1.0, with latest CommonServiceLocator v.2.0.1

**Comment by tillig** [comment]
CSL 2.x is not compatible with the 1.x series. Using Autofac.CSL 4.1 with CSL 1.4 should work.

We'll need an Autofac.CSL 5.0 package for CSL 2.x due to the incompatibilities.

**Comment by alexmg** [comment]
I just pushed a 4.2.0 package but should have made it 5.0. Will push 5.0 now as I have to add back explicit net45 support.

**Comment by alexmg** [comment]
@tillig Do you think we really need to jump to 5.0 given we didn't actually introduce a breaking change?

**Comment by tillig** [comment]
I was never clear on how semver worked for breaking changes introduced by dependencies... But I know I get pretty irritated when I take a 0.1 release of something and it drags along a breaking change with it, causing me to have to roll back a bunch of packages. The semver.org doc says you should be able to upgrade your own dependencies as a 0.1 increment but heads into "use your best judgement" on more complex situations.

Sort of moot now the 5.0 is coming for .NET 4.5 support.

**Comment by alexmg** [comment]
I have currently hidden the 4.2.0 release and put the net45 addition into a 4.2.1 package but that is only on MyGet at this point. I'll update to 5.0 so that on our feed versioning goes 4.0 -> 4.1 -> 5.0 instead of 4.0 -> 4.1 -> 4.2.1 which is kind of gross. 😃

**Comment by alexmg** [comment]
I have pushed the 5.0 package to NuGet which has been upgraded to `CommonServiceLocator` 2.0.1. It supports .NET Framework 4.5 and .NET Standard 2.0.
