### ISSUE TITLE
Is this Autofac.Extras.CommonServiceLocator 5.0.0 compatible with uap10.0.16299?

### ISSUE THREAD

**Issue by spspli** [autofac/Autofac.Extras.CommonServiceLocator#7]
I refer to this Autofac.Extras.CommonServiceLocator 5.0.0 in my UWP project which targets uap10.0.16299, I can build in visual studio 2017 but when I use nuget restore MySolution.sln, I got error saying this package only supports - net45 and netstandard2.0. Is this the case? Is there any plan it will be compatible with uap10.0.16299 in the near future? I don't understand why in visual studio no such error.

**Comment by tillig** [comment]
Please don't double post - it means we have to answer the same question in two places. I will answer on your original question [here](https://stackoverflow.com/q/49803801/8116).
